name: "BUG反馈"
description: LocyanFrp的部分行为不符合预期
title: "BUG反馈 <在此处简单描述>"
labels: ["🐛Bug"]

body:
  - type: input
    id: version
    attributes:
      label: 当前使用的LocyanFrp版本
      description: 设置
    validations:
      required: true

  - type: textarea
    id: expectation
    attributes:
      label: 你的预期
      description: 预期LocyanFrp应该的反应
      placeholder: |
        1. ...
    validations:
      required: true

  - type: textarea
    id: in_fact
    attributes:
      label: 实际上的反应
      placeholder: |
        1. ...
    validations:
      required: true
